# Generated by Django 4.2.7 on 2026-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecache',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moviecache',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
